# Generated by Django 2.1.7 on 2019-04-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchats',
            name='ShareToken',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
