# Generated by Django 2.1.7 on 2019-04-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190422_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousevents',
            name='GroupId',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miscellaneousevents',
            name='ShareToken',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemsetevents',
            name='GroupId',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemsetevents',
            name='ShareToken',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsevents',
            name='GroupId',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsevents',
            name='ShareToken',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportationevents',
            name='GroupId',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportationevents',
            name='ShareToken',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videogamesevents',
            name='GroupId',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videogamesevents',
            name='ShareToken',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingoutevents',
            name='GroupId',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingoutevents',
            name='ShareToken',
            field=models.CharField(default='filler', max_length=50),
            preserve_default=False,
        ),
    ]
