# Generated by Django 2.1.7 on 2019-05-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20190423_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousevents',
            name='UserId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problemsetevents',
            name='UserId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sportsevents',
            name='UserId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportationevents',
            name='UserId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videogamesevents',
            name='UserId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workingoutevents',
            name='UserId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
