# Generated by Django 2.1.7 on 2019-05-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190501_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousevents',
            name='ShareToken',
            field=models.CharField(default='filler', max_length=50),
        ),
    ]
