# Generated by Django 2.1.7 on 2019-05-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_miscellaneousevents_sharetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousevents',
            name='MakerToken',
            field=models.CharField(default='filler', max_length=50),
        ),
        migrations.AddField(
            model_name='problemsetevents',
            name='MakerToken',
            field=models.CharField(default='filler', max_length=50),
        ),
        migrations.AddField(
            model_name='sportsevents',
            name='MakerToken',
            field=models.CharField(default='filler', max_length=50),
        ),
        migrations.AddField(
            model_name='transportationevents',
            name='MakerToken',
            field=models.CharField(default='filler', max_length=50),
        ),
        migrations.AddField(
            model_name='videogamesevents',
            name='MakerToken',
            field=models.CharField(default='filler', max_length=50),
        ),
        migrations.AddField(
            model_name='workingoutevents',
            name='MakerToken',
            field=models.CharField(default='filler', max_length=50),
        ),
    ]
