# Generated by Django 2.1.7 on 2019-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20190501_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousevents',
            name='CategoryName',
            field=models.CharField(default='miscellaneous', max_length=50),
        ),
        migrations.AddField(
            model_name='problemsetevents',
            name='CategoryName',
            field=models.CharField(default='problemset', max_length=50),
        ),
        migrations.AddField(
            model_name='sportsevents',
            name='CategoryName',
            field=models.CharField(default='sports', max_length=50),
        ),
        migrations.AddField(
            model_name='transportationevents',
            name='CategoryName',
            field=models.CharField(default='transportation', max_length=50),
        ),
        migrations.AddField(
            model_name='videogamesevents',
            name='CategoryName',
            field=models.CharField(default='videogames', max_length=50),
        ),
        migrations.AddField(
            model_name='workingoutevents',
            name='CategoryName',
            field=models.CharField(default='workingout', max_length=50),
        ),
    ]
