# Generated by Django 2.1.7 on 2019-05-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20190502_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miscellaneousevents',
            old_name='text',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='problemsetevents',
            old_name='text',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sportsevents',
            old_name='text',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transportationevents',
            old_name='text',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='videogamesevents',
            old_name='text',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='workingoutevents',
            old_name='text',
            new_name='date',
        ),
        migrations.AddField(
            model_name='miscellaneousevents',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='miscellaneousevents',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='problemsetevents',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='problemsetevents',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sportsevents',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sportsevents',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transportationevents',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transportationevents',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='videogamesevents',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='videogamesevents',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workingoutevents',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workingoutevents',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='miscellaneousevents',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='problemsetevents',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sportsevents',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transportationevents',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='videogamesevents',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workingoutevents',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
