# Generated by Django 2.1.7 on 2019-05-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20190504_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsevents',
            name='date',
            field=models.DateField(),
        ),
    ]
