# Generated by Django 2.1.7 on 2019-05-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20190507_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneousevents',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='problemsetevents',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transportationevents',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='videogamesevents',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workingoutevents',
            name='date',
            field=models.DateField(),
        ),
    ]
